### ISSUE TITLE
Make tagged releases

### ISSUE THREAD

**Issue by PureTryOut** [gras64/learning-skill#7]
Hey, thanks for this skill!

I've been packaging Mycroft for Alpine Linux (which I think is the first distribution to do so) and am currently packaging all the different skills available. The idea is to make all skills available as distro packages and not use the current Mycroft marketplace and Pip to install them. I'd love to package your skill as well, but will need a tagged (`git tag`) release to do so.

Please consider making tagged release so that distributions like Alpine Linux and in the future others can package them and keep track of updates.

**Comment by gras64** [comment]
thanks for the hint. I have done

**Comment by PureTryOut** [comment]
Thanks! You can view the progress on getting it in the repositories [here](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/7742).
